### ISSUE TITLE
Revoke reference tokens 

### ISSUE THREAD

**Issue by NvanWeeghel** [rr-wfm/IdentityServerConfig#3]
Userstory;
As a developer, I want to be able to revoke a reference token so that it can no longer be used.

Acceptance criteria:
- [x] The developer must be authorized to revoke the reference token.
- [x] The expiration date of the token must be set to the current date.
- [x] There must be a confirmation before the token can be removed.
- [x] The status of the reference token is set to "expired".

**Comment by jmezach** [comment]
@NvanWeeghel I think we'll not only want the user to be authenticated to do this, but to also have **authorization** to perform the revoke action. For example, some users might be able to only see the available reference tokens, while others are also allowed to revoke them.

**Comment by NvanWeeghel** [comment]
This was a translation error and has now been fixed
